Set default shell to zsh

diff --git a/run_once_install-packages.sh.tmpl b/run_once_install-packages.sh.tmpl
--- a/run_once_install-packages.sh.tmpl
+++ b/run_once_install-packages.sh.tmpl
@@ -13,3 +13,7 @@ packages="${packages} git zsh"
 {{ else if eq .chezmoi.osRelease.id "alpine" }}
 {{ .sudo }}apk add ${packages}
 {{ end }}
+
+if ! chsh -s $(which zsh) $USER; then 
+    echo "Failed to change default shell to `zsh`.
+fi
